configName: pic32mz_ef_sk
folderName: ''
format_version: v1.0
frameworkPath: D:\11_Repo\01_H3\h3
processor: PIC32MZ2048EFH144
projectName: ''
settings:
  PackageFilter: crypto;dev_packs;net;core;core_apps_pic32mz_ef;core_apps_pic32mz_w1;bsp;quick_docs;usb;cryptoauthlib;wireless_wifi;csp;harmony-services;wireless_system_pic32mzw1_wfi32e01;wireless_apps_pic32mzw1_wfi32e01;net_apps_pic32mz
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: ./dev_packs/arm/CMSIS/5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: ./dev_packs/Microchip/PIC32MZ-EF_DFP/1.3.58/atdf/PIC32MZ2048EFH144.atdf
